# yaml-language-server: $schema=https://github.com/Azure/deployment-environments/releases/download/2022-11-11-preview/manifest.schema.json
name: App-Service-with-Cosmos
version: 1.0.0
summary: Azure APP Service with Cosmos Environment
description: Deploys an Azure App Service with Cosmos, it is compatible with azd.
runner: ARM
templatePath: azuredeploy.json

parameters:
  - id: environmentName
    name: environmentName
    description: 'Name of the Web App.'
    type: string
    required: true
  - id: repoUrl
    name: repoUrl
    type: string
    description: Path the the application source code
    default: "https://github.com/azure-samples/todo-nodejs-mongo"
    allowed:
      - "https://github.com/azure-samples/todo-java-mongo"
      - "https://github.com/azure-samples/todo-nodejs-mongo"
      - "https://github.com/azure-samples/todo-python-mongo"
    
    

