name: KeyVault
summary: Environment that deploys a KeyVault
description: Deploys an environment with a KeyVault
runner: ARM
templatePath: azuredeploy.json
parameters:
- id: "keyVaultName"
  name: "keyVaultName"
  description: "Name of Key Vault being deployed, must be globally unique"
  required: true
  type: "string"
