name: FunctionAppParameters
summary: This is Function app deployment utilizing parameters for the name and location of the Function App.
description: Deploys an function app.
templatePath: azuredeploy.json
parameters:
- id: "name"
  name: "name"
  description: "Name of the function app"
  type: "string"
  default: ""
  required: false
- id: "location"
  name: "location"
  description: "Location to deploy the environment resources"
  type: "string"
  default: "[resourceGroup().location]"
  required: false
runner: arm
